**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/creating-reading-and-writing).**

---

# Introduction

The first step in most data analytics projects is reading the data file. In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

Run the code cell below to load libraries you will need (including code to check your answers).

In [10]:
import pandas as pd
pd.set_option('display.max_rows', 5)
from learntools.core import binder; binder.bind(globals())
from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")

Setup complete.

# Exercises

## 1.

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://storage.googleapis.com/kaggle-media/learn/images/Ax3pp2A.png)

In [1]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits.
# Importing the required library
import pandas as pd

# Creating a DataFrame matching the fruit data
fruits = pd.DataFrame({
    'Fruit': ['Apple', 'Banana', 'Orange', 'Mango', 'Grapes'],
    'Color': ['Red', 'Yellow', 'Orange', 'Yellow', 'Purple'],
    'Quantity': [10, 15, 8, 5, 20]
})

# Display the DataFrame to verify
fruits

    Fruit   Color  Quantity
0   Apple     Red        10
1  Banana  Yellow        15
2  Orange  Orange         8
3   Mango  Yellow         5
4  Grapes  Purple        20

In [ ]:
#q1.hint()
#q1.solution()

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://storage.googleapis.com/kaggle-media/learn/images/CHPn7ZF.png)

In [2]:
# Importing the required library
import pandas as pd

# Creating the fruit_sales DataFrame
fruit_sales = pd.DataFrame({
    'Fruit': ['Apple', 'Banana', 'Orange', 'Mango', 'Grapes'],
    'Quantity Sold': [50, 120, 80, 60, 100],
    'Price per Unit': [1.2, 0.5, 0.8, 1.5, 2.0],
    'Total Sales': [60, 60, 64, 90, 200]
})

# Display the DataFrame
fruit_sales

    Fruit  Quantity Sold  Price per Unit  Total Sales
0   Apple             50             1.2           60
1  Banana            120             0.5           60
2  Orange             80             0.8           64
3   Mango             60             1.5           90
4  Grapes            100             2.0          200

In [ ]:
#q2.hint()
#q2.solution()

## 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [5]:
import pandas as pd

# Creating the ingredients Series
ingredients = pd.Series(
    data=['4 cups', '1 cup', '2 large', '1 can'],
    index=['Flour', 'Milk', 'Eggs', 'Spam'],
    name='Dinner'
)

# Display to verify
print(ingredients)

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [ ]:
#q3.hint()
#q3.solution()

## 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://storage.googleapis.com/kaggle-media/learn/images/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [8]:
# Reading the wine reviews CSV file into a DataFrame
reviews = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv')

# Display first 5 rows to verify
reviews.head()


reviews

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...,...
150925,150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [ ]:
#q4.hint()
#q4.solution()

## 5.

Run the cell below to create and display a DataFrame called `animals`:

In [9]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In the cell below, write code to save this DataFrame to disk as a csv file with the name `cows_and_goats.csv`.

In [11]:
# Creating the animals DataFrame
animals = pd.DataFrame({
    'Cows': [12, 20],
    'Goats': [22, 19]
}, index=['Year 1', 'Year 2'])

# Display the DataFrame
print(animals)

# Save the DataFrame to a CSV file
animals.to_csv('cows_and_goats.csv')

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [ ]:
#q5.hint()
#q5.solution()

# Keep going

Move on to learn about **[indexing, selecting and assigning](https://www.kaggle.com/residentmario/indexing-selecting-assigning)**.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*